In [ ]:
import numpy as np

In [3]:
#Question 1- Create a numpy array starting from 2 till 50 with a stepsize of 3.
arr= np.arange(2,51,3)
print (arr)
print(type(arr))

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50]
<class 'numpy.ndarray'>


In [11]:
#Question 2- Accept two lists of 5 elements each from the user.
#            Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

list1=[]
list2=[]

print("Enter 5 elements for 1st list:")
for i in range(5):
  num=int(input("Enter number:"))
  list1.append(num)

print("\nEnter 5 elements for 2nd list:")
for i in range(5):
  num=int(input("Enter number:"))
  list2.append(num)

arr1=np.array(list1)
arr2=np.array(list2)

print("\narray 1:",arr1)
print("array 2:",arr2)

concatArray=np.concatenate((arr1,arr2))
print("\nConcatenated array:",concatArray)
print("Sorted Concatenated array:",np.sort(concatArray))

Enter 5 elements for 1st list:
Enter number:10
Enter number:90
Enter number:56
Enter number:67
Enter number:35

Enter 5 elements for 2nd list:
Enter number:19
Enter number:9
Enter number:64
Enter number:53
Enter number:78

array 1: [10 90 56 67 35]
array 2: [19  9 64 53 78]

Concatenated array: [10 90 56 67 35 19  9 64 53 78]
Sorted Concatenated array: [ 9 10 19 35 53 56 64 67 78 90]


In [15]:
#Question 3- Write a code snippet to find the dimensions of a ndarray and its size.
arr3=np.array([[1,3,7],[9,6,5]])
arr4=np.array([[[1,3,7],[9,6,5]],[[10,19,20],[29,16,15]]])

print("Array 1:\n",arr3)
print("\nArray 2:\n",arr4)

print("\nArray 1 dimensions:",arr3.ndim)
print("Array 2 dimensions:",arr4.ndim)

print("\nArray 1 size:",arr3.size)
print("Array 2 size:",arr4.size)

Array 1:
 [[1 3 7]
 [9 6 5]]

Array 2:
 [[[ 1  3  7]
  [ 9  6  5]]

 [[10 19 20]
  [29 16 15]]]

Array 1 dimensions: 2
Array 2 dimensions: 3

Array 1 size: 6
Array 2 size: 12


In [21]:
#Question 4- How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet
#            Hint: np.newaxis, np.expand_dims
arr5=np.arange(12)
print("Array:",arr5)
print("Array dimensions:",arr5.ndim)
print("Array shape:",arr5.shape)

#np.newaxis
#Converting 1D array to row vector
print("\nConversion of 1D to 2D array using np.newaxis:")
rowVec_arr5 = arr5[np.newaxis, :]
print("Dimensions of array post conversion to row vector:",rowVec_arr5.ndim)
print("Shape of array post conversion to row vector:",rowVec_arr5.shape)

#Converting 1D array to column vector
colVec_arr5 = arr5[:, np.newaxis]
print("\nDimensions of array post conversion to column vector:",colVec_arr5.ndim)
print("Shape of array post conversion to column vector:",colVec_arr5.shape)

#np.expand_dims
#Converting 1D array to row vector
print("\n\nConversion of 1D to 2D array using np.expand_dims:")
rowVec1_arr5 = np.expand_dims(arr5, axis=0)
print("Dimensions of array post conversion to row vector:",rowVec1_arr5.ndim)
print("Shape of array post conversion to row vector:",rowVec1_arr5.shape)

#Converting 1D array to column vector
colVec1_arr5 = np.expand_dims(arr5, axis=1)
print("\nDimensions of array post conversion to column vector:",colVec1_arr5.ndim)
print("Shape of array post conversion to column vector:",colVec1_arr5.shape)

Array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Array dimensions: 1
Array shape: (12,)

Conversion of 1D to 2D array using np.newaxis:
Dimensions of array post conversion to row vector: 2
Shape of array post conversion to row vector: (1, 12)

Dimensions of array post conversion to column vector: 2
Shape of array post conversion to column vector: (12, 1)


Conversion of 1D to 2D array using np.expand_dims:
Dimensions of array post conversion to row vector: 2
Shape of array post conversion to row vector: (1, 12)

Dimensions of array post conversion to column vector: 2
Shape of array post conversion to column vector: (12, 1)


In [23]:
#Question 5- Consider two square numpy arrays. Stack them vertically and horizontally.
#            Hint: Use vstack(), hstack()

# creating 2 arrays by squaring input values
arr6 = np.square([1, 2, 5, 7, 8])
arr7 = np.square([3, 4, 6, 9, 10])

print("Array 1:",arr6)
print("Array 2:",arr7)

# stacking the squared arrays
print("\nHorizontal stacking:", np.hstack((arr6, arr7)))
print("Vertical stacking :", np.vstack((arr6, arr7)))

Array 1: [ 1  4 25 49 64]
Array 2: [  9  16  36  81 100]

Horizontal stacking: [  1   4  25  49  64   9  16  36  81 100]
Vertical stacking : [[  1   4  25  49  64]
 [  9  16  36  81 100]]


In [26]:
#Question6- How to get unique items and counts of unique items?
arr8 = np.array( [12,12,25,12,18,25,12,18, 56,12,18,20] )
print("Original array:",arr8)
#using unique method from numpy
unique_ele, count_uniqueEle = np.unique(arr8, return_counts=True)
print("\nUnique Elements with frequency:\n",np.asarray((unique_ele, count_uniqueEle)).T)

Original array: [12 12 25 12 18 25 12 18 56 12 18 20]

Unique Elements with frequency:
 [[12  5]
 [18  3]
 [20  1]
 [25  2]
 [56  1]]
